image: docker:20

services:
  - docker:20-dind

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay

stages:
  - test

test:
  stage: test
  services:
  - name: docker:20-dind
    command: ["--tls=false"]
  script:
    - docker-compose run --rm api sh -c "npm run migration:run:ci && npm run test:ci"
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml